### ISSUE TITLE
PHP Fatal error when downloading a test on Arch Linux

### ISSUE THREAD

**Issue by willfindlay** [phoronix-test-suite/phoronix-test-suite#498]
I'm getting the following PHP error when downloading a new test:
```
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: int / CurlHandle in /usr/share/phoronix-test-suite/pts-core/objects/pts_network.php:303
Stack trace:
#0 [internal function]: pts_network::curl_status_callback()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_network.php(187): curl_exec()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_network.php(113): pts_network::curl_download()
#3 /usr/share/phoronix-test-suite/pts-core/objects/client/pts_test_installer.php(414): pts_network::download_file()
#4 /usr/share/phoronix-test-suite/pts-core/objects/client/pts_test_installer.php(797): pts_test_installer::download_test_files()
#5 /usr/share/phoronix-test-suite/pts-core/objects/client/pts_test_installer.php(150): pts_test_installer::install_test_process()
#6 /usr/share/phoronix-test-suite/pts-core/objects/client/pts_test_installer.php(76): pts_test_installer::start_install()
#7 /usr/share/phoronix-test-suite/pts-core/commands/install_test.php(41): pts_test_installer::standard_install()
#8 /usr/share/phoronix-test-suite/pts-core/objects/client/pts_client.php(1524): install_test::run()
#9 /usr/share/phoronix-test-suite/pts-core/phoronix-test-suite.php(152): pts_client::execute_command()
#10 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_network.php on line 303
```

This happens when I download any test that is not already cached.

PHP version is: 
```
PHP 8.0.1 (cli) (built: Jan  8 2021 16:19:26) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.1, Copyright (c) Zend Technologies
```
Phoronix Test Suite version is: Phoronix Test Suite v10.2.0

**Comment by michaellarabel** [comment]
Thanks, was able to reproduce when building PHP8 with cURL enabled. Missed it previously for PTS also working fine with PHP without cURL.

This should be fixed today with https://github.com/phoronix-test-suite/phoronix-test-suite/commit/0963f5fcd082a55a11c31be071b9152ee01b9d35 and will be part of PTS 10.2.1 this week. Thanks!
