### ISSUE TITLE
error with executive-summary

### ISSUE THREAD

**Issue by m4v** [phoronix-test-suite/phoronix-test-suite#548]
Phoronix Test Suite v10.4.0 (Ibestad)

executive-summary (and other stuff that depends on it like export to pdf) fails if, I believe, the machine that comes ahead has 100% wins.

Output from my terminal showing how I reproduced this:

```
$ phoronix-test-suite wins-and-losses benchmark               


   benchmark

   WINS:                
   i5-11400:  8   [88.9%] 
   i7-6700:    1   [11.1%] 
                                   
   LOSSES:              
   i5-3317U:    8   [88.9%] 
   i3-2100:      1   [11.1%] 
   TESTS COUNTED: 9

$ phoronix-test-suite executive-summary benchmark


benchmark

i5-11400 had the most wins, coming in first place for 88% of the tests.

Based on the geometric mean of all complete results, the fastest (i5-11400) was 7.723x the speed of the slowest (i5-3317U).

$ phoronix-test-suite remove-result-from-result-file benchmark



1: Unigine Valley
   Resolution: 1920 x 1080 - Mode: Fullscreen - Renderer: OpenGL
2: PolyBench-C
   Test: Covariance Computation
3: PolyBench-C
   Test: Correlation Computation
4: PolyBench-C
   Test: 3 Matrix Multiplications
5: FFTW
   Build: Float + SSE - Size: 2D FFT Size 512
6: FFTW
   Build: Float + SSE - Size: 1D FFT Size 4096
7: Timed MPlayer Compilation
   Time To Compile
8: Sysbench
   Test: RAM / Memory
9: Sysbench
   Test: CPU
** Multiple items can be selected, delimit by a comma. **
Select the result(s) to remove: 1
    Do you want to view the results in your web browser (Y/n): n

$ phoronix-test-suite wins-and-losses benchmark             


   benchmark

   WINS:                 
   i5-11400:  8   [100.0%] 
                                    
   LOSSES:               
   i5-3317U:    8   [100.0%] 
   TESTS COUNTED: 8

$ phoronix-test-suite executive-summary benchmark             



    [NOTICE] Trying to get property 'test_result_buffer' of non-object in pts_result_file_analyzer:392
PHP Fatal error:  Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:392
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/commands/executive_summary.php(38): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/client/pts_client.php(1550): executive_summary::run()
#2 /usr/share/phoronix-test-suite/pts-core/phoronix-test-suite.php(152): pts_client::execute_command()
#3 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 392
```

**Comment by michaellarabel** [comment]
This issue should have already been corrected a while ago on Git and will be found in the next stable release.

**Comment by tranphuquy19** [comment]
@michaellarabel 

I got the same error when exporting 2 Test Results at the same time on Phoronix Test Suite v10.8.2

What I did:
-> Select 2 Test Results > click COMPARE > EXPORT BENCHMARK DATA > RESULT FILE TO PDF

Here is the log
```log
[56] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44192 [200]: GET /?result/6s6goo7gx1ss8g400ckw4oowo0ws8cc,3rpgwocsuy0w4g0o4kc0kcw0wcc4w0o
[56] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44192 Closing
[54] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44252 Accepted
[51] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44250 Accepted
[51] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44250 [200]: (null) /phoromatic.js?2022033010820
[51] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44250 Closing
[54] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44252 [200]: GET /phoromatic.css?20220330
[54] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44252 Closing
[45] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44254 Accepted
[54] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44256 Accepted
[45] [Wed Mar 30 09:02:31 2022] 172.27.150.26:44254 [200]: (null) /images/phoromatic_logo.svg
[45] [Wed Mar 30 09:02:31 2022] 172.27.150.26:44254 Closing
[54] [Wed Mar 30 09:02:31 2022] 172.27.150.26:44256 [200]: GET /images/rss.svg
[54] [Wed Mar 30 09:02:31 2022] 172.27.150.26:44256 Closing
[56] [Wed Mar 30 09:02:35 2022] 172.27.150.26:44270 Accepted
[53] [Wed Mar 30 09:02:41 2022] 172.27.150.26:44284 Accepted
[56] [Wed Mar 30 09:03:01 2022] PHP Fatal error:  Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[56] [Wed Mar 30 09:03:01 2022] 172.27.150.26:44270 [500]: GET /?result/6s6goo7gx1ss8g400ckw4oowo0ws8cc,3rpgwocsuy0w4g0o4kc0kcw0wcc4w0o&export=pdf - Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[56] [Wed Mar 30 09:03:01 2022] 172.27.150.26:44270 Closing
[53] [Wed Mar 30 09:03:26 2022] PHP Fatal error:  Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[53] [Wed Mar 30 09:03:26 2022] 172.27.150.26:44284 [500]: GET /?result/6s6goo7gx1ss8g400ckw4oowo0ws8cc,3rpgwocsuy0w4g0o4kc0kcw0wcc4w0o&export=pdf - Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[53] [Wed Mar 30 09:03:26 2022] 172.27.150.26:44284 Closing
[57] [Wed Mar 30 09:03:32 2022] 172.27.150.26:44388 Accepted
[52] [Wed Mar 30 09:03:52 2022] 172.27.150.26:44432 Accepted
[57] [Wed Mar 30 09:03:57 2022] PHP Fatal error:  Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[57] [Wed Mar 30 09:03:57 2022] 172.27.150.26:44388 [500]: GET /?result/6s6goo7gx1ss8g400ckw4oowo0ws8cc,3rpgwocsuy0w4g0o4kc0kcw0wcc4w0o&export=pdf - Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[57] [Wed Mar 30 09:03:57 2022] 172.27.150.26:44388 Closing
[52] [Wed Mar 30 09:04:23 2022] PHP Fatal error:  Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[52] [Wed Mar 30 09:04:23 2022] 172.27.150.26:44432 [500]: GET /?result/6s6goo7gx1ss8g400ckw4oowo0ws8cc,3rpgwocsuy0w4g0o4kc0kcw0wcc4w0o&export=pdf - Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[52] [Wed Mar 30 09:04:23 2022] 172.27.150.26:44432 Closing
```

```xml
<?xml version="1.0"?>
<!--phoronix-test-suite.xml-->
<PhoronixTestSuite>
  <Options>
    <OpenBenchmarking>
      <AnonymousUsageReporting>TRUE</AnonymousUsageReporting>
      <IndexCacheTTL>3</IndexCacheTTL>
      <AlwaysUploadSystemLogs>FALSE</AlwaysUploadSystemLogs>
      <AllowResultUploadsToOpenBenchmarking>TRUE</AllowResultUploadsToOpenBenchmarking>
    </OpenBenchmarking>
    <General>
      <DefaultBrowser></DefaultBrowser>
      <UsePhodeviCache>TRUE</UsePhodeviCache>
      <DefaultDisplayMode>DEFAULT</DefaultDisplayMode>
      <PhoromaticServers></PhoromaticServers>
      <FullOutput>FALSE</FullOutput>
      <ColoredConsole>AUTO</ColoredConsole>
    </General>
    <Modules>
      <AutoLoadModules>toggle_screensaver, update_checker, perf_tips, ob_auto_compare, load_dynamic_result_viewer</AutoLoadModules>
    </Modules>
    <Installation>
      <RemoveDownloadFiles>FALSE</RemoveDownloadFiles>
      <SearchMediaForCache>TRUE</SearchMediaForCache>
      <SymLinkFilesFromCache>FALSE</SymLinkFilesFromCache>
      <PromptForDownloadMirror>FALSE</PromptForDownloadMirror>
      <EnvironmentDirectory>~/.phoronix-test-suite/installed-tests/</EnvironmentDirectory>
      <CacheDirectory>~/.phoronix-test-suite/download-cache/</CacheDirectory>
    </Installation>
    <Testing>
      <SaveSystemLogs>TRUE</SaveSystemLogs>
      <SaveInstallationLogs>TRUE</SaveInstallationLogs>
      <SaveTestLogs>TRUE</SaveTestLogs>
      <RemoveTestInstallOnCompletion></RemoveTestInstallOnCompletion>
      <ResultsDirectory>~/.phoronix-test-suite/test-results/</ResultsDirectory>
      <AlwaysUploadResultsToOpenBenchmarking>FALSE</AlwaysUploadResultsToOpenBenchmarking>
      <AutoSortRunQueue>TRUE</AutoSortRunQueue>
      <ShowPostRunStatistics>TRUE</ShowPostRunStatistics>
    </Testing>
    <TestResultValidation>
      <DynamicRunCount>TRUE</DynamicRunCount>
      <LimitDynamicToTestLength>20</LimitDynamicToTestLength>
      <StandardDeviationThreshold>2.5</StandardDeviationThreshold>
      <ExportResultsTo></ExportResultsTo>
      <MinimalTestTime>2</MinimalTestTime>
      <DropNoisyResults>FALSE</DropNoisyResults>
    </TestResultValidation>
    <ResultViewer>
      <WebPort>8082</WebPort>
      <LimitAccessToLocalHost>FALSE</LimitAccessToLocalHost>
      <AccessKey></AccessKey>
      <AllowSavingResultChanges>TRUE</AllowSavingResultChanges>
      <AllowDeletingResults>TRUE</AllowDeletingResults>
    </ResultViewer>
    <BatchMode>
      <SaveResults>TRUE</SaveResults>
      <OpenBrowser>FALSE</OpenBrowser>
      <UploadResults>TRUE</UploadResults>
      <PromptForTestIdentifier>TRUE</PromptForTestIdentifier>
      <PromptForTestDescription>TRUE</PromptForTestDescription>
      <PromptSaveName>TRUE</PromptSaveName>
      <RunAllTestCombinations>TRUE</RunAllTestCombinations>
      <Configured>FALSE</Configured>
    </BatchMode>
    <Networking>
      <NoInternetCommunication>FALSE</NoInternetCommunication>
      <NoNetworkCommunication>FALSE</NoNetworkCommunication>
      <Timeout>20</Timeout>
      <ProxyAddress></ProxyAddress>
      <ProxyPort></ProxyPort>
      <ProxyUser></ProxyUser>
      <ProxyPassword></ProxyPassword>
    </Networking>
    <Server>
      <RemoteAccessPort>8080</RemoteAccessPort>
      <Password></Password>
      <WebSocketPort>8081</WebSocketPort>
      <AdvertiseServiceZeroConf>TRUE</AdvertiseServiceZeroConf>
      <AdvertiseServiceOpenBenchmarkRelay>TRUE</AdvertiseServiceOpenBenchmarkRelay>
      <PhoromaticStorage>~/.phoronix-test-suite/phoromatic/</PhoromaticStorage>
    </Server>
  </Options>
</PhoronixTestSuite>
```

**Comment by marymizrahi** [comment]
I created a new issue from the above since this one is closed.
