### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Undefined constant "GLOB_BRACE" in /root/benchmark/phoronix-test-suite/pts-core/objects/phodevi/sensors/hdd_read_speed.php:65

### ISSUE THREAD

**Issue by HougeLangley** [phoronix-test-suite/phoronix-test-suite#565]
```
PHP PCNTL support is needed if wishing to gracefully interrupt testing with signals.
PHP Fatal error:  Uncaught Error: Undefined constant "GLOB_BRACE" in /root/benchmark/phoronix-test-suite/pts-core/objects/phodevi/sensors/hdd_read_speed.php:65
Stack trace:
#0 /root/benchmark/phoronix-test-suite/pts-core/objects/client/pts_stress_run_manager.php(217): hdd_read_speed::get_supported_devices()
#1 /root/benchmark/phoronix-test-suite/pts-core/objects/client/pts_stress_run_manager.php(134): pts_stress_run_manager->multi_test_stress_run_execute()
#2 /root/benchmark/phoronix-test-suite/pts-core/commands/stress_run.php(36): pts_stress_run_manager::stress_run()
#3 /root/benchmark/phoronix-test-suite/pts-core/objects/client/pts_client.php(1556): stress_run::run()
#4 /root/benchmark/phoronix-test-suite/pts-core/commands/interactive.php(141): pts_client::execute_command()
#5 /root/benchmark/phoronix-test-suite/pts-core/objects/client/pts_client.php(1556): interactive::run()
#6 /root/benchmark/phoronix-test-suite/pts-core/phoronix-test-suite.php(152): pts_client::execute_command()
#7 {main}
  thrown in /root/benchmark/phoronix-test-suite/pts-core/objects/phodevi/sensors/hdd_read_speed.php on line 65
```

**Comment by HougeLangley** [comment]
```
phoronix-test-suite git:(master) ./phoronix-test-suite interactive


Phoronix Test Suite v10.6.1
Interactive Benchmarking


  PROCESSOR:              ARMv8 Cortex-A72 @ 1.42GHz
    Core Count:           4
    Thread Count:         6
    Scaling Driver:       cpufreq-dt performance

  GRAPHICS:               rockchip
    Monitor:              X EQUIP
    Screen:               1920x1080

  MOTHERBOARD:            Xiaobao Nas I
    Chipset:              Rockchip RK3399

  MEMORY:                 4096MB

  DISK:                   63GB LX64G
    File-System:          ext4
    Mount Options:        relatime rw
    Disk Details:         Block Size: 4096

  OPERATING SYSTEM:       Gentoo/Linux
    Kernel:               5.15.2-gentoo-GENTOO (aarch64)
    Compiler:             GCC 11.2.0
    Security:             itlb_multihit: Not affected
                          + l1tf: Not affected
                          + mds: Not affected
                          + meltdown: Not affected
                          + spec_store_bypass: Vulnerable
                          + spectre_v1: Mitigation of __user pointer sanitization
                          + spectre_v2: Vulnerable
                          + srbds: Not affected
                          + tsx_async_abort: Not affected




1: Run A Test / Benchmark
2: Run A Suite      [A Collection Of Tests]
3: Run A Stress Test      [Concurrent Benchmarks For Heavy System Load]
4: Show System Hardware / Software Information
5: Show Available System Sensors
6: List Available Tests
7: List Recommended Tests
8: Search Tests / Suites / Results
9: Exit
Select Task: 3

1:   7-Zip Compression                                  - Processor
2:   ACES DGEMM                                         - Processor
3:   AI Benchmark Alpha                                 - System
4:   AOBench                                            - Processor
5:   AOM AV1                                            - Processor
6:   AOM AV1                                            - Processor
7:   ASKAP                                              - System
8:   ASTC Encoder                                       - System
9:   Aircrack-ng                                        - Processor
10:  Algebraic Multi-Grid Benchmark                     - Processor
11:  Apache Benchmark                                   - System
12:  Apache Cassandra                                   - System
13:  Apache CouchDB                                     - System
14:  Apache HBase                                       - System
15:  Apache HTTP Server                                 - System
16:  Apache Siege                                       - System
17:  Application Start-up Time                          - Disk
18:  BLAKE2                                             - Processor
19:  BRL-CAD                                            - System
20:  BYTE Unix Benchmark                                - Processor
21:  Basis Universal                                    - System
22:  BenchmarkMutex                                     - System
23:  Blender                                            - System
24:  BlogBench                                          - Disk
25:  BlogBench                                          - Disk
26:  Bork File Encrypter                                - Processor
27:  Botan                                              - Processor
28:  Build2                                             - Processor
29:  Bullet Physics Engine                              - Processor
30:  C-Blosc                                            - Processor
31:  C-Ray                                              - Processor
32:  CLOMP                                              - Processor
33:  CacheBench                                         - Processor
34:  Caffe                                              - System
35:  Chia Blockchain VDF                                - Processor
36:  CloudSuite Data Analytics                          - System
37:  CloudSuite Graph Analytics                         - System
38:  CloudSuite In-Memory Analytics                     - System
39:  CloudSuite Media Streaming                         - System
40:  CloudSuite Web Serving                             - System
41:  CloverLeaf                                         - Processor
42:  CoMD OpenCL                                        - System
43:  Compile Bench                                      - Disk
44:  Core-Latency                                       - Processor
45:  Coremark                                           - Processor
46:  CppPerformanceBenchmarks                           - System
47:  Crypto++                                           - Processor
48:  Cryptsetup                                         - System
49:  Cyclictest                                         - System
50:  Cython Benchmark                                   - Processor
51:  DaCapo Benchmark                                   - Processor
52:  Darktable                                          - System
53:  Darmstadt Automotive Parallel Heterogeneous Suite  - System
54:  Dbench                                             - Disk
55:  Dbench                                             - Disk
56:  Dolfyn                                             - Processor
57:  ECP-CANDLE                                         - System
58:  Etcpak                                             - Processor
59:  Ethereum Ethminer                                  - System
60:  Ethr                                               - Network
61:  FAHBench                                           - Graphics
62:  FFTE                                               - Processor
63:  FFTW                                               - Processor
64:  FFmpeg                                             - Processor
65:  FLAC Audio Encoding                                - Processor
66:  FS-Mark                                            - Disk
67:  Facebook RocksDB                                   - System
68:  Fhourstones                                        - Processor
69:  FinanceBench                                       - System
70:  Flexible IO Tester                                 - Disk
71:  Flexible IO Tester                                 - Disk
72:  G'MIC                                              - System
73:  GEGL                                               - System
74:  GIMP                                               - System
75:  GNU GMP GMPbench                                   - Processor
76:  GNU MPC                                            - Processor
77:  GNU Octave Benchmark                               - System
78:  GNU Radio                                          - Processor
79:  GPAW                                               - System
80:  GROMACS                                            - System
81:  Gcrypt Library                                     - Processor
82:  Git                                                - System
83:  GnuPG                                              - Processor
84:  GnuPG                                              - System
85:  Go Benchmarks                                      - Processor
86:  Google Draco                                       - System
87:  Google SynthMark                                   - Processor
88:  GraphicsMagick                                     - Processor
89:  Gzip Compression                                   - Processor
90:  HPC Challenge                                      - Processor
91:  HPL Linpack                                        - Processor
92:  Hackbench                                          - Processor
93:  HammerDB - PostgreSQL                              - System
94:  Helsing                                            - Processor
95:  Hierarchical INTegration                           - System
96:  High Performance Conjugate Gradient                - Processor
97:  Himeno Benchmark                                   - Processor
98:  Hugin                                              - System
99:  IOR                                                - Disk
100: IOzone                                             - Disk
101: IPC_benchmark                                      - Processor
102: Idle Power Usage                                   - System
103: InfluxDB                                           - System
104: Inkscape                                           - System
105: Intel MPI Benchmarks                               - System
106: Interbench                                         - System
107: JPEG XL Decoding libjxl                            - Processor
108: JPEG XL libjxl                                     - Processor
109: Java Gradle Build                                  - Processor
110: Java Graphics Basic Acceptance Test                - Processor
111: Java JMH                                           - System
112: Java SciMark                                       - Processor
113: John The Ripper                                    - Processor
114: JuliaGPU                                           - System
115: KeyDB                                              - System
116: Kripke                                             - System
117: Kvazaar                                            - Processor
118: LAME MP3 Encoding                                  - Processor
119: LAMMPS Molecular Dynamics Simulator                - Processor
120: LULESH                                             - Processor
121: LZ4 Compression                                    - Processor
122: LZMA Compression                                   - Processor
123: LeelaChessZero                                     - Processor
124: LevelDB                                            - Disk
125: LibRaw                                             - Processor
126: LibreOffice                                        - System
127: Liquid-DSP                                         - Processor
128: Loopback TCP Network Performance                   - Network
129: LuaJIT                                             - Processor
130: LuaRadio                                           - Processor
131: Lulesh OpenCL                                      - System
132: MBW                                                - Memory
133: MPV                                                - System
134: MandelGPU                                          - System
135: MandelbulbGPU                                      - System
136: MariaDB                                            - System
137: Memcached mcperf                                   - System
138: Memtier_benchmark                                  - System
139: Mencoder                                           - Processor
140: Minion                                             - Processor
141: Mixbench                                           - Graphics
142: Mlpack Benchmark                                   - System
143: Mobile Neural Network                              - System
144: Montage Astronomical Image Mosaic Engine           - Processor
145: Monte Carlo Simulations of Ionised Nebulae         - Processor
146: Multichase Pointer Chaser                          - Processor
147: MySQL                                              - System
148: N-Queens                                           - Processor
149: NAS Parallel Benchmarks                            - Processor
150: NCNN                                               - System
151: NVIDIA TensorRT Inference                          - Graphics
152: NWChem                                             - Processor
153: Nebular Empirical Analysis Tool                    - Processor
154: Netperf                                            - Network
155: Nettle                                             - Processor
156: Nginx                                              - System
157: Ngspice                                            - Processor
158: Node.js Express HTTP Load Test                     - Processor
159: Node.js Octane Benchmark                           - Processor
160: Node.js V8 Web Tooling Benchmark                   - Processor
161: Numenta Anomaly Benchmark                          - System
162: Numpy Benchmark                                    - Processor
163: Nuttcp                                             - Network
164: OCRMyPDF                                           - System
165: ONNX Runtime                                       - System
166: OSBench                                            - OS
167: Open FMM Nero2D                                    - Processor
168: Open Porous Media                                  - Processor
169: Open Porous Media                                  - Processor
170: Open Porous Media Git                              - Processor
171: OpenCV                                             - System
172: OpenCV Benchmark                                   - Processor
173: OpenDwarfs                                         - System
174: OpenFOAM                                           - Processor
175: OpenSCAD                                           - System
176: OpenSSL                                            - Processor
177: OpenSSL                                            - Processor
178: OpenVINO                                           - System
179: Optcarrot                                          - System
180: Opus Codec Encoding                                - Processor
181: PBZIP2 Compression                                 - Processor
182: PHP Micro Benchmarks                               - System
183: PHPBench                                           - System
184: PJSIP                                              - Processor
185: POV-Ray                                            - Processor
186: Parallel BZIP2 Compression                         - Processor
187: Parboil                                            - Processor
188: Pennant                                            - Processor
189: Perl Benchmarks                                    - Processor
190: Phoronix Test Suite Self Test                      - System
191: Pjdfstest                                          - Disk
192: PlaidML                                            - System
193: PolyBench-C                                        - Processor
194: Polyhedron Fortran Benchmarks                      - Processor
195: PostMark                                           - Disk
196: PostgreSQL pgbench                                 - System
197: Powertop Wakeups                                   - Processor
198: Primesieve                                         - Processor
199: PyBench                                            - System
200: PyHPC Benchmarks                                   - System
201: PyMongo Inserts                                    - System
202: PyPerformance                                      - System
203: QMCPACK                                            - Processor
204: Qmlbench                                           - System
205: QuantLib                                           - Processor
206: Quantum ESPRESSO                                   - Processor
207: R Benchmark                                        - Processor
208: RAMspeed SMP                                       - Memory
209: RELION                                             - Processor
210: RNNoise                                            - Processor
211: RawTherapee                                        - System
212: Redis                                              - System
213: Redis Memtier / Redis Benchmark                    - System
214: Renaissance                                        - Processor
215: Rodinia                                            - Processor
216: Rust Mandelbrot                                    - Processor
217: Rust Prime Benchmark                               - Processor
218: SHOC Scalable HeterOgeneous Computing              - Graphics
219: SMART Disk Self-Report                             - Disk
220: SMHasher                                           - Processor
221: SQLite                                             - Disk
222: SQLite                                             - Disk
223: SQLite Speedtest                                   - System
224: SVT-AV1                                            - Processor
225: SVT-AV1                                            - Processor
226: SVT-HEVC                                           - Processor
227: SVT-HEVC                                           - Processor
228: SVT-VP9                                            - Processor
229: SVT-VP9                                            - Processor
230: Sample Pass Fail                                   - System
231: Sample Pi Program                                  - Processor
232: Schbench                                           - System
233: SciMark                                            - Processor
234: Scikit-Learn                                       - System
235: SecureMark                                         - Processor
236: Serial Loopback Test                               - System
237: SmallPT GPU                                        - System
238: Smallpt                                            - Processor
239: Sockperf                                           - OS
240: Stargate Digital Audio Workstation                 - Processor
241: Stockfish                                          - Processor
242: Stream                                             - Memory
243: Stress-NG                                          - System
244: Stressful Application Test                         - Memory
245: Sudokut                                            - Processor
246: Sunflow Rendering System                           - System
247: Swet                                               - Processor
248: Sysbench                                           - System
249: System BZIP2 Decompression                         - Processor
250: System GZIP Decompression                          - Processor
251: System Libxml2 Parsing                             - Processor
252: System XZ Decompression                            - Processor
253: TNN                                                - System
254: TSCP                                               - Processor
255: TTSIOD 3D Renderer                                 - Processor
256: Tachyon                                            - Processor
257: TensorFlow Lite                                    - System
258: Tensorflow                                         - System
259: Tesseract OCR                                      - System
260: Threaded I/O Tester                                - Disk
261: Timed Apache Compilation                           - Processor
262: Timed Clash Compilation                            - Processor
263: Timed Eigen Compilation                            - Processor
264: Timed Erlang/OTP Compilation                       - Processor
265: Timed FFmpeg Compilation                           - Processor
266: Timed GCC Compilation                              - Processor
267: Timed GDB GNU Debugger Compilation                 - Processor
268: Timed Godot Game Engine Compilation                - Processor
269: Timed HMMer Search                                 - Processor
270: Timed Idle                                         - System
271: Timed ImageMagick Compilation                      - Processor
272: Timed LLVM Compilation                             - Processor
273: Timed Linux Kernel Compilation                     - Processor
274: Timed MAFFT Alignment                              - Processor
275: Timed MPlayer Compilation                          - Processor
276: Timed Mesa Compilation                             - Processor
277: Timed MrBayes Analysis                             - Processor
278: Timed Node.js Compilation                          - Processor
279: Timed PHP Compilation                              - Processor
280: Timed Wasmer Compilation                           - Processor
281: Tinymembench                                       - Memory
282: Tungsten Renderer                                  - Processor
283: Unpacking Firefox                                  - System
284: Unpacking The Linux Kernel                         - Disk
285: VOSK Speech Recognition Toolkit                    - Processor
286: VP9 libvpx Encoding                                - Processor
287: VP9 libvpx Encoding                                - Processor
288: ViennaCL                                           - System
289: WRF                                                - System
290: WavPack Audio Encoding                             - System
291: WebP Image Encode                                  - Processor
292: WebP2 Image Encode                                 - Processor
293: WireGuard + Linux Networking Stack Stress Test     - Network
294: XZ Compression                                     - Processor
295: Xcompact3d Incompact3d                             - Processor
296: Xmrig                                              - Processor
297: Xsbench                                            - System
298: Xsbench OpenCL                                     - System
299: YafaRay                                            - Processor
300: Zstd Compression                                   - Processor
301: Zstd Compression                                   - Processor
302: asmFish                                            - Processor
303: cl-mem                                             - Graphics
304: clpeak                                             - System
305: clpeak                                             - System
306: ctx_clock                                          - System
307: dav1d                                              - Processor
308: dav1d                                              - Processor
309: eSpeak-NG Speech Engine                            - Processor
310: ebizzy                                             - Processor
311: glibc bench                                        - Processor
312: hdparm Timed Disk Reads                            - Disk
313: iPerf                                              - Network
314: libavif avifenc                                    - Processor
315: libgav1                                            - Processor
316: libjpeg-turbo tjbench                              - System
317: librsvg                                            - System
318: lzbench                                            - Processor
319: m-queens                                           - Processor
320: miniFE                                             - Processor
321: nginx                                              - System
322: oneAPI Level Zero Tests                            - System
323: oneDNN                                             - Processor
324: oneDNN MKL-DNN                                     - Processor
325: perf-bench                                         - OS
326: pmbench                                            - Memory
327: rav1e                                              - Processor
328: rav1e                                              - Processor
329: rays1bench                                         - Processor
330: simdjson                                           - Processor
331: srsLTE                                             - Processor
332: srsRAN                                             - Processor
333: t-test1                                            - Memory
334: toyBrot Fractal Generator                          - Processor
335: x264                                               - Processor
336: x265                                               - Processor
337: x265                                               - Processor
** Multiple items can be selected, delimit by a comma. **
Select Test(s): 1,31,47,136,294,337

Number of tests to run concurrently: 6

Number of minutes to stress run: 30
    Evaluating External Test Dependencies ................................................................................................
    Installed:     pts/compress-7zip-1.7.1
    Installed:     pts/c-ray-1.2.0
    Installed:     pts/cryptopp-1.0.1
    Installed:     pts/mysqlslap-1.2.0
    Installed:     pts/compress-xz-1.1.0
    Installed:     git/x265-1.1.0

STRESS-RUN ENVIRONMENT VARIABLES:

PTS_CONCURRENT_TEST_RUNS set; running 6 tests concurrently.


TOTAL_LOOP_TIME set; running tests for 30 minutes


TEST_RESULTS_NAME is not set; set the TEST_RESULTS_NAME environment variable if wanting to save the sensor summary to a result file.



Crypto++ 8.2:
    pts/cryptopp-1.0.1
    Processor Test Configuration
        1: Unkeyed Algorithms
        2: Keyed Algorithms
        3: Integer + Elliptic Curve Public Key Algorithms
        4: All Algorithms                                 [This option can be very time consuming.]
        5: Test All Options
        ** Multiple items can be selected, delimit by a comma. **
        Test: 1



MariaDB 10.6.4:
    pts/mysqlslap-1.2.0
    System Test Configuration
        1:  1
        2:  8
        3:  16
        4:  32
        5:  64
        6:  128
        7:  256
        8:  512
        9:  1024
        10: 2048
        11: 4096
        12: Test All Options
        ** Multiple items can be selected, delimit by a comma. **
        Clients: 5

PHP PCNTL support is needed if wishing to gracefully interrupt testing with signals.
PHP Fatal error:  Uncaught Error: Undefined constant "GLOB_BRACE" in /root/benchmark/phoronix-test-suite/pts-core/objects/phodevi/sensors/hdd_read_speed.php:65
Stack trace:
#0 /root/benchmark/phoronix-test-suite/pts-core/objects/client/pts_stress_run_manager.php(217): hdd_read_speed::get_supported_devices()
#1 /root/benchmark/phoronix-test-suite/pts-core/objects/client/pts_stress_run_manager.php(134): pts_stress_run_manager->multi_test_stress_run_execute()
#2 /root/benchmark/phoronix-test-suite/pts-core/commands/stress_run.php(36): pts_stress_run_manager::stress_run()
#3 /root/benchmark/phoronix-test-suite/pts-core/objects/client/pts_client.php(1556): stress_run::run()
#4 /root/benchmark/phoronix-test-suite/pts-core/commands/interactive.php(141): pts_client::execute_command()
#5 /root/benchmark/phoronix-test-suite/pts-core/objects/client/pts_client.php(1556): interactive::run()
#6 /root/benchmark/phoronix-test-suite/pts-core/phoronix-test-suite.php(152): pts_client::execute_command()
#7 {main}
  thrown in /root/benchmark/phoronix-test-suite/pts-core/objects/phodevi/sensors/hdd_read_speed.php on line 65
```
