### ISSUE TITLE
Export benchmark data to PDF fails

### ISSUE THREAD

**Issue by marymizrahi** [phoronix-test-suite/phoronix-test-suite#613]
@michaellarabel 

I got the same error when exporting 2 Test Results at the same time on Phoronix Test Suite v10.8.2

What I did:
-> Select 2 Test Results > click COMPARE > EXPORT BENCHMARK DATA > RESULT FILE TO PDF

Here is the log
```log
[56] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44192 [200]: GET /?result/6s6goo7gx1ss8g400ckw4oowo0ws8cc,3rpgwocsuy0w4g0o4kc0kcw0wcc4w0o
[56] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44192 Closing
[54] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44252 Accepted
[51] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44250 Accepted
[51] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44250 [200]: (null) /phoromatic.js?2022033010820
[51] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44250 Closing
[54] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44252 [200]: GET /phoromatic.css?20220330
[54] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44252 Closing
[45] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44254 Accepted
[54] [Wed Mar 30 09:02:30 2022] 172.27.150.26:44256 Accepted
[45] [Wed Mar 30 09:02:31 2022] 172.27.150.26:44254 [200]: (null) /images/phoromatic_logo.svg
[45] [Wed Mar 30 09:02:31 2022] 172.27.150.26:44254 Closing
[54] [Wed Mar 30 09:02:31 2022] 172.27.150.26:44256 [200]: GET /images/rss.svg
[54] [Wed Mar 30 09:02:31 2022] 172.27.150.26:44256 Closing
[56] [Wed Mar 30 09:02:35 2022] 172.27.150.26:44270 Accepted
[53] [Wed Mar 30 09:02:41 2022] 172.27.150.26:44284 Accepted
[56] [Wed Mar 30 09:03:01 2022] PHP Fatal error:  Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[56] [Wed Mar 30 09:03:01 2022] 172.27.150.26:44270 [500]: GET /?result/6s6goo7gx1ss8g400ckw4oowo0ws8cc,3rpgwocsuy0w4g0o4kc0kcw0wcc4w0o&export=pdf - Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[56] [Wed Mar 30 09:03:01 2022] 172.27.150.26:44270 Closing
[53] [Wed Mar 30 09:03:26 2022] PHP Fatal error:  Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[53] [Wed Mar 30 09:03:26 2022] 172.27.150.26:44284 [500]: GET /?result/6s6goo7gx1ss8g400ckw4oowo0ws8cc,3rpgwocsuy0w4g0o4kc0kcw0wcc4w0o&export=pdf - Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[53] [Wed Mar 30 09:03:26 2022] 172.27.150.26:44284 Closing
[57] [Wed Mar 30 09:03:32 2022] 172.27.150.26:44388 Accepted
[52] [Wed Mar 30 09:03:52 2022] 172.27.150.26:44432 Accepted
[57] [Wed Mar 30 09:03:57 2022] PHP Fatal error:  Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[57] [Wed Mar 30 09:03:57 2022] 172.27.150.26:44388 [500]: GET /?result/6s6goo7gx1ss8g400ckw4oowo0ws8cc,3rpgwocsuy0w4g0o4kc0kcw0wcc4w0o&export=pdf - Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[57] [Wed Mar 30 09:03:57 2022] 172.27.150.26:44388 Closing
[52] [Wed Mar 30 09:04:23 2022] PHP Fatal error:  Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[52] [Wed Mar 30 09:04:23 2022] 172.27.150.26:44432 [500]: GET /?result/6s6goo7gx1ss8g400ckw4oowo0ws8cc,3rpgwocsuy0w4g0o4kc0kcw0wcc4w0o&export=pdf - Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:395
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(947): pts_result_file_analyzer::generate_executive_summary()
#1 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(956): pts_result_file_output::result_file_to_pdf()
#2 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(1181): pts_result_viewer_embed::process_result_export_pre_render()
#3 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_viewer_embed.php(137): pts_result_viewer_embed::process_helper_html()
#4 /usr/share/phoronix-test-suite/pts-core/phoromatic/pages/phoromatic_result.php(277): pts_result_viewer_embed->get_html()
#5 /usr/share/phoronix-test-suite/pts-core/phoromatic/public_html/index.php(90): phoromatic_result::render_page_process()
#6 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 395
[52] [Wed Mar 30 09:04:23 2022] 172.27.150.26:44432 Closing
```

```xml
<?xml version="1.0"?>
<!--phoronix-test-suite.xml-->
<PhoronixTestSuite>
  <Options>
    <OpenBenchmarking>
      <AnonymousUsageReporting>TRUE</AnonymousUsageReporting>
      <IndexCacheTTL>3</IndexCacheTTL>
      <AlwaysUploadSystemLogs>FALSE</AlwaysUploadSystemLogs>
      <AllowResultUploadsToOpenBenchmarking>TRUE</AllowResultUploadsToOpenBenchmarking>
    </OpenBenchmarking>
    <General>
      <DefaultBrowser></DefaultBrowser>
      <UsePhodeviCache>TRUE</UsePhodeviCache>
      <DefaultDisplayMode>DEFAULT</DefaultDisplayMode>
      <PhoromaticServers></PhoromaticServers>
      <FullOutput>FALSE</FullOutput>
      <ColoredConsole>AUTO</ColoredConsole>
    </General>
    <Modules>
      <AutoLoadModules>toggle_screensaver, update_checker, perf_tips, ob_auto_compare, load_dynamic_result_viewer</AutoLoadModules>
    </Modules>
    <Installation>
      <RemoveDownloadFiles>FALSE</RemoveDownloadFiles>
      <SearchMediaForCache>TRUE</SearchMediaForCache>
      <SymLinkFilesFromCache>FALSE</SymLinkFilesFromCache>
      <PromptForDownloadMirror>FALSE</PromptForDownloadMirror>
      <EnvironmentDirectory>~/.phoronix-test-suite/installed-tests/</EnvironmentDirectory>
      <CacheDirectory>~/.phoronix-test-suite/download-cache/</CacheDirectory>
    </Installation>
    <Testing>
      <SaveSystemLogs>TRUE</SaveSystemLogs>
      <SaveInstallationLogs>TRUE</SaveInstallationLogs>
      <SaveTestLogs>TRUE</SaveTestLogs>
      <RemoveTestInstallOnCompletion></RemoveTestInstallOnCompletion>
      <ResultsDirectory>~/.phoronix-test-suite/test-results/</ResultsDirectory>
      <AlwaysUploadResultsToOpenBenchmarking>FALSE</AlwaysUploadResultsToOpenBenchmarking>
      <AutoSortRunQueue>TRUE</AutoSortRunQueue>
      <ShowPostRunStatistics>TRUE</ShowPostRunStatistics>
    </Testing>
    <TestResultValidation>
      <DynamicRunCount>TRUE</DynamicRunCount>
      <LimitDynamicToTestLength>20</LimitDynamicToTestLength>
      <StandardDeviationThreshold>2.5</StandardDeviationThreshold>
      <ExportResultsTo></ExportResultsTo>
      <MinimalTestTime>2</MinimalTestTime>
      <DropNoisyResults>FALSE</DropNoisyResults>
    </TestResultValidation>
    <ResultViewer>
      <WebPort>8082</WebPort>
      <LimitAccessToLocalHost>FALSE</LimitAccessToLocalHost>
      <AccessKey></AccessKey>
      <AllowSavingResultChanges>TRUE</AllowSavingResultChanges>
      <AllowDeletingResults>TRUE</AllowDeletingResults>
    </ResultViewer>
    <BatchMode>
      <SaveResults>TRUE</SaveResults>
      <OpenBrowser>FALSE</OpenBrowser>
      <UploadResults>TRUE</UploadResults>
      <PromptForTestIdentifier>TRUE</PromptForTestIdentifier>
      <PromptForTestDescription>TRUE</PromptForTestDescription>
      <PromptSaveName>TRUE</PromptSaveName>
      <RunAllTestCombinations>TRUE</RunAllTestCombinations>
      <Configured>FALSE</Configured>
    </BatchMode>
    <Networking>
      <NoInternetCommunication>FALSE</NoInternetCommunication>
      <NoNetworkCommunication>FALSE</NoNetworkCommunication>
      <Timeout>20</Timeout>
      <ProxyAddress></ProxyAddress>
      <ProxyPort></ProxyPort>
      <ProxyUser></ProxyUser>
      <ProxyPassword></ProxyPassword>
    </Networking>
    <Server>
      <RemoteAccessPort>8080</RemoteAccessPort>
      <Password></Password>
      <WebSocketPort>8081</WebSocketPort>
      <AdvertiseServiceZeroConf>TRUE</AdvertiseServiceZeroConf>
      <AdvertiseServiceOpenBenchmarkRelay>TRUE</AdvertiseServiceOpenBenchmarkRelay>
      <PhoromaticStorage>~/.phoronix-test-suite/phoromatic/</PhoromaticStorage>
    </Server>
  </Options>
</PhoronixTestSuite>
```

_Originally posted by @tranphuquy19 in https://github.com/phoronix-test-suite/phoronix-test-suite/issues/548#issuecomment-1082834085_

**Comment by michaellarabel** [comment]
This was already fixed in Git some weeks ago. Or in web browser if just going to File > Print [To PDF] should be a similar view as well.

**Comment by marymizrahi** [comment]
It's not in 10.8.2.  Was it fixed after that release?
