### ISSUE TITLE
Tests could not be located (windows install)

### ISSUE THREAD

**Issue by Spybull** [phoronix-test-suite/phoronix-test-suite#652]
phoronix-test-suite.bat - couldn't install all dependencies, only php and VC_redist.x64, but cygwin doesn't auto installed

Error message for run shell:
```
phoronix-test-suite-10.8.4>phoronix-test-suite.bat shell
Starting the Phoronix Test Suite



Phoronix Test Suite v10.8.4
Interactive Shell

Generating Shell Cache...
Refreshing OpenBenchmarking.org Repository Cache...

Fatal error: Uncaught Error: Class 'microsoft_dependency_handler' not found in C:\Users\Admin\Downloads\phoronix-test-suite-10.8.4\phoronix-test-suite-10.8.4\pts-core\objects\phodevi\components\phodevi_system.php:656
Stack trace:
#0 C:\Users\Admin\Downloads\phoronix-test-suite-10.8.4\phoronix-test-suite-10.8.4\pts-core\objects\phodevi\phodevi.php(501): phodevi_system::sw_security_features()
#1 C:\Users\Admin\Downloads\phoronix-test-suite-10.8.4\phoronix-test-suite-10.8.4\pts-core\objects\phodevi\phodevi.php(375): phodevi::read_property('system', 'security-featur...')
#2 C:\Users\Admin\Downloads\phoronix-test-suite-10.8.4\phoronix-test-suite-10.8.4\pts-core\commands\shell.php(37): phodevi::system_centralized_view()
#3 C:\Users\Admin\Downloads\phoronix-test-suite-10.8.4\phoronix-test-suite-10.8.4\pts-core\objects\client\pts_client.php(1333): shell::run(Array)
#4 C:\Users\Admin\Downloads\phoronix-test-suite-10.8.4\phoronix-test-suite-10.8.4\pts-core\phoronix-test-suite.php(155): pts_client::execute_command('shell', Array)
#5 in C:\Users\Admin\Downloads\phoronix-test-suite-10.8.4\phoronix-test-suite-10.8.4\pts-core\objects\phodevi\components\phodevi_system.php on line 656
```

Error message for all installed test:
`  The test executable for pts/gputest-1.3.2 could not be located. Looking for gputest in C:\Users\Admin\.phoronix-test-suite\installed-tests\\pts/gputest-1.3.2\`

This happen on:
```
Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz   3.60 GHz
Windows 10 Pro 21H2
```

**Comment by gelonsoft** [comment]
This is cause you Windows is not English and phoronix bug.
Bug in phoronix in 	phoronix-test-suite\pts-core\objects\phodevi\components\phodevi_system.php:
====
'vendor-identifier' => new phodevi_device_property('sw_vendor_identifier', phodevi::smart_caching),
====
It uses first word of phodevi::read_property('system', 'operating-system'); 
which is localized. For example, for russian it would be Майкрософт, so phoronix will try to load "майкрософт_dependency_handler.php" instead of microsoft_dependency_handler.php file.
