### ISSUE TITLE
Module tests failing due to Call to a member function get_results_identifier() on null

### ISSUE THREAD

**Issue by tmarkettos** [phoronix-test-suite/phoronix-test-suite#730]
Ubuntu 22.04 x86_64:

```
$ sudo apt install ./phoronix-test-suite_10.8.4_all.deb
...
$ phoronix-test-suite test-module perf_per_dollar
...
Calling: __startup()
Calling: __pre_option_process()
Calling: __pre_install_process()
Calling: __pre_test_download()
Calling: __interim_test_download()
Calling: __post_test_download()
Calling: __pre_test_install()
Calling: __post_test_install()
Calling: __post_install_process()
Calling: __pre_run_process()
PHP Fatal error:  Uncaught Error: Call to a member function get_results_identifier() on null in /usr/share/phoronix-test-suite/pts-core/modules/perf_per_dollar.php:104
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/client/pts_module_manager.php(86): perf_per_dollar::__pre_run_process()
#1 /usr/share/phoronix-test-suite/pts-core/objects/client/pts_module_manager.php(112): pts_module_manager::module_call()
#2 /usr/share/phoronix-test-suite/pts-core/commands/test_module.php(45): pts_module_manager::module_process()
#3 /usr/share/phoronix-test-suite/pts-core/objects/client/pts_client.php(1333): test_module::run()
#4 /usr/share/phoronix-test-suite/pts-core/phoronix-test-suite.php(155): pts_client::execute_command()
#5 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/modules/perf_per_dollar.php on line 104
```

The same applies to `system-monitor`, `linux_perf` and `report_test_run_times`.

**Comment by xpardee-create** [comment]
We observed the same error with system_monitor module on phoronix test suite 10.8.4. Is there an update or something I can do to fix the issue?
