### ISSUE TITLE
Installing glmark2 raises `ModuleNotFoundError: No module named 'imp'` with Python 3.12 system

### ISSUE THREAD

**Issue by kakakaya** [phoronix-test-suite/phoronix-test-suite#801]
Hello!

I'm trying to use glmark2 benchmark, but not working well.

I typed: `phoronix-test-suite benchmark glmark2`, and output is:

```
    Evaluating External Test Dependencies ........................................................................................................................................................................................

Phoronix Test Suite v10.8.4

    To Install:    pts/glmark2-1.4.0

    Determining File Requirements ................................................................................................................................................................................................
    Searching Download Caches ....................................................................................................................................................................................................

    1 Test To Install
        59MB Of Disk Space Is Needed
        1 Second Estimated Install Time

    pts/glmark2-1.4.0:
        Test Installation 1 of 1
        1 File Needed [8.93 MB / 1 Minute]
        File Found: glmark2-2023.01.tar.gz                                                                                                                                                                                [8.93MB]
        Approximate Install Size: 59 MB
        Installing Test @ 14:49:14
egrep: warning: egrep is obsolescent; using grep -E
            The installer exited with a non-zero exit status.
            ERROR: ModuleNotFoundError: No module named 'imp'
            LOG: ~/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/install-failed.log


    [PROBLEM] pts/glmark2-1.4.0 is not installed.
```

And, its error log as below:
```
/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Utils.py:413: SyntaxWarning: invalid escape sequence '\d'
  return re.split('\d+$',s)[0]
/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/ConfigSet.py:7: SyntaxWarning: invalid escape sequence '\ '
  re_imp=re.compile('^(#)*?([^#=]*?)\ =\ (.*?)$',re.M)
/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/ansiterm.py:178: SyntaxWarning: invalid escape sequence '\['
  ansi_tokens=re.compile('(?:\x1b\[([0-9?;]*)([a-zA-Z])|([^\x1b]+))')
Traceback (most recent call last):
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/./waf", line 163, in <module>
    from waflib import Scripting
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Scripting.py", line 6, in <module>
    from waflib import Utils,Configure,Logs,Options,ConfigSet,Context,Errors,Build,Node
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Configure.py", line 6, in <module>
    from waflib import ConfigSet,Utils,Options,Logs,Context,Build,Errors
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Options.py", line 6, in <module>
    from waflib import Logs,Utils,Context,Errors
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Context.py", line 5, in <module>
    import os,re,imp,sys
ModuleNotFoundError: No module named 'imp'
Traceback (most recent call last):
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/./waf", line 163, in <module>
    from waflib import Scripting
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Scripting.py", line 6, in <module>
    from waflib import Utils,Configure,Logs,Options,ConfigSet,Context,Errors,Build,Node
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Configure.py", line 6, in <module>
    from waflib import ConfigSet,Utils,Options,Logs,Context,Build,Errors
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Options.py", line 6, in <module>
    from waflib import Logs,Utils,Context,Errors
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Context.py", line 5, in <module>
    import os,re,imp,sys
ModuleNotFoundError: No module named 'imp'
Traceback (most recent call last):
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/./waf", line 163, in <module>
    from waflib import Scripting
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Scripting.py", line 6, in <module>
    from waflib import Utils,Configure,Logs,Options,ConfigSet,Context,Errors,Build,Node
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Configure.py", line 6, in <module>
    from waflib import ConfigSet,Utils,Options,Logs,Context,Build,Errors
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Options.py", line 6, in <module>
    from waflib import Logs,Utils,Context,Errors
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Context.py", line 5, in <module>
    import os,re,imp,sys
ModuleNotFoundError: No module named 'imp'
```

----

### Environment

```
Phoronix Test Suite v10.8.4

OS: EndeavourOS Linux x86_64
Host: MS-7B86 3.0
Kernel: 6.10.2-arch1-1
Uptime: 27 mins
Packages: 1273 (pacman)
Shell: fish 3.7.1
Resolution: 1920x1080
DE: Plasma 6.1.4
WM: kwin
Theme: Breeze-Dark [GTK2], Breeze [GTK3]
Icons: breeze-dark [GTK2/3]
Terminal: zellij
CPU: AMD Ryzen 5 3600X (12) @ 3.800GHz
GPU: NVIDIA GeForce RTX 3070
Memory: 4520MiB / 32045MiB
```

I've installed phoenix-test-suite via AUR, but I believe it doesn't matter...
https://aur.archlinux.org/packages/phoronix-test-suite

**Comment by bentenjamin** [comment]
I have the same issue on my Fedora 40 install

**Comment by FabioLolix** [comment]
Can't evince which python module is 'imp' by looking at https://github.com/glmark2/glmark2?tab=readme-ov-file and https://github.com/glmark2/glmark2/blob/master/INSTALL

**Comment by FabioLolix** [comment]
According to https://github.com/glmark2/glmark2/issues/191#issuecomment-1359438834

Build system should be switched to meson
